#onion by PacMan (Andrij Shvets) v1.2.3 [Android] beta

import webbrowser

print("Onion")
print("by")
print("PacMan")
print("")
print("v1.2.3 [beta]  ")
print("")
print(" #Нет_войны! ")
print("")
print("v1.2.3 [beta & глобальное обновление!] ")
print ("Исправил огромное количество ошибок...") 
print("")
print (" /a поисковики, /b  Сайты. Просто напишите английскую а или b.")
what = input ("/")

if what == "a":
    print("http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/")
    print("http://xmh57jrknzkhv6y3ls3ubitzfqnkrwxhopf5aygthi7d6rplyvk3noyd.onion/")
    print("http://2fd6cemt4gmccflhm6imvdfvli3nf7zn6rfrwpsy7uhxrgbypvwf5fad.onion")
    print("")
    print("stop")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("Сейчас откроется новая вкладка вашего браузера...")
    print("")
    print("")
    print("")
    print("1...")
    print("")
    print("")
    print("2...")
    print("")
    print("")
    print("3...")
    webbrowser.open('https://t.me/i2p_3218', new=2)
    print("подпишись на меня в Telegram ^_^ ")
    

elif what == "b":
    print("http://kpzscgdqezpen5zpnc4gky5vx4r56thl5syq2x45j6hbjy5w7tjilwid.onion/blog/")
    print("http://55gexkiyipqq2tvrkkrcgcc62yuqcil2bgk4k64dle6g62mdov7otqid.onion")
    print("http://5ajc5sk4plsiem2g.onion/")
    print("http://videonwcswhrqynk.onion")
    print("http://ovgl57qc3a5abwqgdhdtssvmydr6f6mjz6ey23thwy63pmbxqmi45iid.onion/")
    print("http://pic2tornetwa6jj2gytmpiz3fyqgir4obar7duyvtsosaohbdey3x2ad.onion/")
    print("http://tmfeedozvp6v65nf.onion/")
    print("http://xmh57jrzrnw6insl.onion/")
    print("http://hss3uro2hsxfogfq.onion/")
    print("http://society44nlbxqdz.onion/group/music")
    print("http://darkweba6le5w52w.onion/")
    print("http://grrmailb3fxpjbwm.onion/")
    print("http://deepmexzsejpzqid3k7knaas2p73dko6kxgpou7oey7vqtmrhopjyqyd.onion/")
    print("http://cr6m2rg4gsydf6yd.onion/")
    print("http://bbbps6itk4pbhuqilhengm3q625fq4ibrzdua6smjaojophaanllgpyd.onion/")
    print("http://torpedodlvreoibyse66ffvrrbvzjdxqi574fduwso2nid6vs2yozxad.onion")
    print("http://hydraruzxpnew4af.onion/register")
    print("http://phobosxilamwcg75xt22id7aywkzol6q6rfl2flipcqoc4e4ahima5id.onion/")
    print("http://cockmailwwfvrtqj.onion")
    print("http://tinhat233xymse34.onion/blog/primers/how-secure-email.html")
    print("http://gh5gewziqmm5twfn2dpwap6t4dwp44emi4smzmw3f5lqc3natfbcpuid.onion/")
    print("https://ezdhgsy2aw7zg54z6dqsutrduhl22moami5zv2zt6urr6vub7gs6wfad.onion/node/19")
    print("http://anospain79hispano5.torpress2sarn7xw.onion/descarga/")
    print("http://bhm5koavobq353j54qichcvzr6uhtri6x4bjjy4xkybgvxkzuslzcqid.onion")
    print("http://nymphetowhsn3gpf.onion/")
    print("http://bhfdotioyenp2qr4.onion/threads/614914/")
    print("http://psychonaut3z5aoz.onion/wiki/")
    print("")
    print("")
    print("Другие onions в нашем канале! ")
    
else:
  print("Errrrrr :D [ошибочка] ")
input()